variables:
  IMAGE_NAME: guillermoroman/k8s-python-app
  IMAGE_TAG: 1.0

stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  tags:
    - docker
  image: python:3.12-slim-bullseye
  before_script:
    - apt-get update && apt-get install make
  script:
    - make test

build_image:
  stage: build
  tags:
    - docker
  image: docker:20.10.16
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_TOKEN
  script:
    - docker build -f ./build/Dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy_app:
  stage: deploy
  variables:
    KUBECONFIG: $KUBECTL_CONFIG_FILE
  tags:
    - docker
  image: guillermoroman/builder_k8s:stable
  script:
    - env
