apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
  - port: 5000
    targetPort: 5000


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  selector:
    matchLabels:
      app: python-app
  replicas: 4
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: guillermoroman/k8s-python-app:1.0
        ports:
        - containerPort: 5000